# Generated by Django 4.2.13 on 2024-12-24 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='coins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
