# Generated by Django 4.2.13 on 2025-01-08 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_body_color_customuser_eye_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='agility',
            field=models.PositiveIntegerField(default=10, help_text="Player's agility attribute."),
        ),
        migrations.AddField(
            model_name='customuser',
            name='defence',
            field=models.PositiveIntegerField(default=10, help_text="Player's defence attribute."),
        ),
        migrations.AddField(
            model_name='customuser',
            name='intelligence',
            field=models.PositiveIntegerField(default=10, help_text="Player's intelligence attribute."),
        ),
        migrations.AddField(
            model_name='customuser',
            name='speed',
            field=models.PositiveIntegerField(default=10, help_text="Player's speed attribute."),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stealth',
            field=models.PositiveIntegerField(default=10, help_text="Player's stealth attribute."),
        ),
        migrations.AddField(
            model_name='customuser',
            name='strength',
            field=models.PositiveIntegerField(default=10, help_text="Player's strength attribute."),
        ),
    ]
