# Generated by Django 4.2.13 on 2024-11-30 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('wings', 'Wings'), ('headpiece', 'Headpiece'), ('armour', 'Armour'), ('melee_weapon', 'Melee_weapon'), ('shield', 'Shield'), ('legs', 'Legs')], max_length=20)),
            ],
        ),
    ]
