# Generated by Django 4.2.13 on 2024-12-24 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('cost', models.PositiveIntegerField()),
                ('item_pool', models.ManyToManyField(related_name='chests', to='inventory.item')),
            ],
        ),
    ]
