# Generated by Django 4.2.13 on 2024-12-03 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_equippeditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='equippeditem',
            name='wings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_wings', to='inventory.item'),
        ),
    ]
