# Generated by Django 4.2.13 on 2024-12-24 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_chest'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rarity',
            field=models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=20),
        ),
    ]
