# Generated by Django 4.2.13 on 2025-01-08 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_marketlisting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketlisting',
            name='listed_price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
