# Generated by Django 4.2.13 on 2025-01-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_marketlisting_listed_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='agility',
            field=models.PositiveIntegerField(default=0, help_text="Player's agility attribute."),
        ),
        migrations.AddField(
            model_name='item',
            name='defence',
            field=models.PositiveIntegerField(default=0, help_text="Player's defence attribute."),
        ),
        migrations.AddField(
            model_name='item',
            name='intelligence',
            field=models.PositiveIntegerField(default=0, help_text="Player's intelligence attribute."),
        ),
        migrations.AddField(
            model_name='item',
            name='speed',
            field=models.PositiveIntegerField(default=0, help_text="Player's speed attribute."),
        ),
        migrations.AddField(
            model_name='item',
            name='stealth',
            field=models.PositiveIntegerField(default=0, help_text="Player's stealth attribute."),
        ),
        migrations.AddField(
            model_name='item',
            name='strength',
            field=models.PositiveIntegerField(default=0, help_text="Player's strength attribute."),
        ),
    ]
