# Generated by Django 4.2.13 on 2025-01-10 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_item_agility_item_defence_item_intelligence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('wings', 'Wings'), ('headpiece', 'Headpiece'), ('armour', 'Armour'), ('melee', 'Melee'), ('shield', 'Shield'), ('legs', 'Legs'), ('coins', 'Coins')], max_length=20),
        ),
    ]
