# Generated by Django 4.2.13 on 2025-01-11 03:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_dungeonsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_description', models.TextField()),
                ('likes', models.TextField()),
                ('dislikes', models.TextField()),
                ('file_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='dungeonsession',
            name='total_rewards_value',
        ),
        migrations.AddField(
            model_name='dungeonsession',
            name='next_item_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dungeonsession',
            name='npc_event_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dungeonsession',
            name='npc_event_triggered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dungeonsession',
            name='paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dungeonsession',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
