# Generated by Django 4.2.13 on 2025-01-12 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_npc_remove_dungeonsession_total_rewards_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dungeonsession',
            name='user_health',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
