# Generated by Django 4.2.13 on 2025-01-12 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_dungeonsession_user_health'),
    ]

    operations = [
        migrations.AddField(
            model_name='dungeonsession',
            name='logs',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
