# Generated by Django 4.2.13 on 2025-01-12 04:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_dungeonsession_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='dungeonsession',
            name='next_escapade_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dungeonsession',
            name='logs',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
