# Generated by Django 4.2.13 on 2025-01-14 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_dungeonsession_next_escapade_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equippeditem',
            name='shield',
        ),
        migrations.AddField(
            model_name='equippeditem',
            name='arm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_arms', to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('wings', 'Wings'), ('headpiece', 'Headpiece'), ('armour', 'Armour'), ('melee', 'Melee'), ('arm', 'Arm'), ('legs', 'Legs'), ('coins', 'Coins')], max_length=20),
        ),
    ]
