# Generated by Django 4.2.13 on 2024-07-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_remove_exercise_muscle_group_exercise_muscle_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
