# Generated by Django 4.2.13 on 2024-11-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_remove_exercise_image_image'),
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='avg_heart_rate',
            field=models.IntegerField(default=110, help_text='Average Heart Rate for Workout'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='mood',
            field=models.IntegerField(default=1, help_text='1-3 From Sad To Happy'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workout',
            name='duration',
            field=models.FloatField(help_text='Duration of workout'),
        ),
        migrations.RemoveField(
            model_name='workout',
            name='exercises_done',
        ),
        migrations.AddField(
            model_name='workout',
            name='exercises_done',
            field=models.ManyToManyField(to='exercises.exercise'),
        ),
    ]
