# Generated by Django 4.2.13 on 2025-01-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='agility_gained',
            field=models.PositiveIntegerField(default=0, help_text="Player's agility attribute."),
        ),
        migrations.AddField(
            model_name='workout',
            name='speed_gained',
            field=models.PositiveIntegerField(default=0, help_text="Player's speed attribute."),
        ),
        migrations.AddField(
            model_name='workout',
            name='strength_gained',
            field=models.PositiveIntegerField(default=0, help_text="Player's strength attribute."),
        ),
    ]
