# Generated by Django 4.2.13 on 2024-11-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_workout_avg_heart_rate_workout_mood_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='energy_burned',
            field=models.FloatField(default=85, help_text='Kcal'),
            preserve_default=False,
        ),
    ]
