# Generated by Django 4.2.13 on 2024-11-04 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0003_workout_energy_burned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='duration',
            field=models.DurationField(help_text='Duration of the workout (e.g., HH:MM:SS)'),
        ),
    ]
