# Generated by Django 4.2.13 on 2024-11-05 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_remove_exercise_image_image'),
        ('logger', '0004_alter_workout_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='muscle_groups',
            field=models.ManyToManyField(to='exercises.musclegroup'),
        ),
    ]
