# Generated by Django 4.2.13 on 2024-11-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_remove_exercise_image_image'),
        ('logger', '0005_workout_muscle_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='muscle_groups',
            field=models.ManyToManyField(blank=True, null=True, to='exercises.musclegroup'),
        ),
    ]
